apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: load-demand-forecasting-model # executable id, must be unique across all your workflows (YAML files)
  annotations:
    scenarios.ai.sap.com/description: "loading demand forecasting model"
    scenarios.ai.sap.com/name: "load-model" # Scenario name should be the use case
    executables.ai.sap.com/description: "Generate metrics"
    executables.ai.sap.com/name: "load-model" # Executable name should describe the workflow in the use case
    artifacts.ai.sap.com/inputmodel.kind: "model" # Helps in suggesting the kind of artifact that can be generated.
    artifacts.ai.sap.com/forecastmodel.kind: "model" # Helps in suggesting the kind of artifact that can be generated.
  labels:
    scenarios.ai.sap.com/id: "load-model"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: mm-credentials-docker # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    inputs:
      artifacts:  # placeholder for cloud storage attachements
        - name: inputmodel # a name for the placeholder
          path: /app/data/model # where to copy in the Dataset in the Docker image
    outputs:
      artifacts:
        - name: forecastmodel # name of the artifact generated, and folder name when placed in S3, complete directory will be `../<executaion_id>/housepricemodel`
          globalName: forecastmodel # local identifier name to the workflow, also used above in annotation
          path: /app/model/ # from which folder in docker image (after running workflow step) copy contents to cloud storage
          archive:
            none:   # specify not to compress while uploading to cloud
              {}
    container:
      image: docker.io/moermansm/demand-forecasting-pipeline:02
      command: ["/bin/sh", "-c"]
      args:
        - "mkdir -p /app/model && python /app/src/load-model.py"
