apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: demand-forecasting-training
  annotations:
    scenarios.ai.sap.com/description: "Training for Demand Forecasting"
    scenarios.ai.sap.com/name: "Training"
    executables.ai.sap.com/description: "Train the demand forecasting model"
    executables.ai.sap.com/name: "demand forecasting training"
    artifacts.ai.sap.com/preprocesseddata.kind: "dataset"
    artifacts.ai.sap.com/forecastingmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "Training"
    ai.sap.com/version: "4.0"
spec:
  imagePullSecrets:
    - name: mm-credentials-docker
  entrypoint: training
    parameters: # placeholder for string like inputs
        - name: SEASON_LENGTH # identifier local to this workflow
  templates:
  - name: training
    steps:
      - name: training-step
        template: train
  - name: train
    inputs:
      artifacts:
        - name: preprocesseddata
          path: /app/data/
    outputs:
      artifacts:
        - name: forecastingmodel
          globalName: forecastingmodel # local identifier name to the workflow, also used above in annotation
          path: /app/model/
    container:
      image: docker.io/moermansm/demand-forecasting-pipeline:03
      command: ["/bin/sh", "-c"]
      env:
        - name : SEASON_LENGTH
          value : "{{workflow.parameters.DT_MAX_DEPTH}}"
      args:
        - >
            set -e && echo "---Start Training---" && python /app/src/train.py && ls -lR /app/model && echo "---End Training---"
